import type { Metadata } from 'next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from '@vercel/analytics/next';
import localFont from 'next/font/local';
import '../styles/styles.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const appleSD = localFont({
  src: [
    { path: '../../public/fonts/AppleSDGothicNeo-Black.woff2', weight: '900' },
    {
      path: '../../public/fonts/AppleSDGothicNeo-ExtraBold.woff2',
      weight: '800',
    },
    { path: '../../public/fonts/AppleSDGothicNeo-Bold.woff2', weight: '700' },
    { path: '../../public/fonts/AppleSDGothicNeo-Medium.woff2', weight: '500' },
    {
      path: '../../public/fonts/AppleSDGothicNeo-SemiBold.woff2',
      weight: '600',
    },
    {
      path: '../../public/fonts/AppleSDGothicNeo-Regular.woff2',
      weight: '400',
    },
    { path: '../../public/fonts/AppleSDGothicNeo-Light.woff2', weight: '300' },
    {
      path: '../../public/fonts/AppleSDGothicNeo-ExtraLight.woff2',
      weight: '200',
    },
    { path: '../../public/fonts/AppleSDGothicNeo-Thin.woff2', weight: '100' },
  ],
  variable: '--font-apple-sd',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR">
      <body className={`${appleSD.variable} antialiased`}>
        <p className="font-appleSD font-light">제1장 총칙</p>
        {children}
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
