name: Lighthouse CI

on:
  push:
    branches: [lighthouse]
  pull_request:

jobs:
  lhci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Start server and run Lighthouse
        run: |
          npm run start &
          npx wait-on http://localhost:3000
          npx lhci autorun \
            --collect.url=http://localhost:3000 \
            --upload.target=temporary-public-storage
